Repository OntimizeWeb/ontimize-web-ngx-charts, pull requests merged in 2023-11, with the labels that each got.

#154 [15.x.x] Fixed error that prevented building the graph the first time
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
Labels: bug

#140 Fixed bug that makes the menu button disappear
  projects/ontimize-web-ngx-charts/src/lib/components/chart-on-demand/o-chart-on-demand.component.html
  projects/ontimize-web-ngx-charts/src/lib/components/chart-on-demand/o-chart-on-demand.component.scss
Labels: bug

#148 Fixed bug with type currency
  ontimize-web-ngx-15.0.0-SNAPSHOT-7.tgz
  package-lock.json
  package.json
  projects/ontimize-web-ngx-charts/src/lib/components/chart-on-demand/o-chart-on-demand.component.ts
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
  projects/ontimize-web-ngx-charts/src/lib/types/currency.type.ts
Labels: bug

#159 [15.x.x] Adapted data to area chart
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
Labels: bug, v15

#160 [15.x.x] Removed nvd3 and d3 references
  projects/ontimize-web-ngx-charts/package.json
  projects/ontimize-web-ngx-charts/src/lib/components/chart-on-demand/o-chart-on-demand-utils.ts
  projects/ontimize-web-ngx-charts/src/lib/components/chart-on-demand/o-chart-on-demand.component.ts
  projects/ontimize-web-ngx-charts/src/lib/models/options/AbstractChartOptions.class.ts
  projects/ontimize-web-ngx-charts/src/lib/models/options/D3LocaleOptions.ts
  projects/ontimize-web-ngx-charts/src/lib/models/options/ForceDirectedGraphOptions.class.ts
  projects/ontimize-web-ngx-charts/src/lib/models/options/RadarChartOptions.class.ts
  projects/ontimize-web-ngx-charts/src/lib/o-models.ts
  projects/ontimize-web-ngx-charts/src/lib/services/d3Locale.service.ts
  projects/ontimize-web-ngx-charts/src/lib/services/index.ts
  projects/ontimize-web-ngx-charts/styles.scss
Labels: bug

#161 [15.x.x] Date format in table for graphs
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
Labels: enhancement, v15

#162 [15.x.x] CHANGELOG 15.0.0-beta.1
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx-charts/package.json
Labels: enhancement, v15

#166 [Quickstart Charts] Release 15.0.0
  .github/workflows/build-release.yml
  .github/workflows/prepare-release.yml
  angular.json
  package-lock.json
  package.json
  src/app/main/area-chart/radar/radar.component.html
  src/app/main/area-chart/stacked-area/stacked-area.component.html
  src/app/main/area-chart/stacked-area/stacked-area.component.ts
  src/app/main/bar-chart/bullet/bullet.component.html
  src/app/main/bar-chart/discrete-bar/discrete-bar.component.html
  src/app/main/bar-chart/discrete-bar/discrete-bar.component.ts
  src/app/main/bar-chart/multi-bar-horizontal/multi-bar-horizontal.component.html
  src/app/main/bar-chart/multi-bar-horizontal/multi-bar-horizontal.component.ts
  src/app/main/bar-chart/multi-bar/multi-bar.component.html
  src/app/main/bar-chart/multi-bar/multi-bar.component.ts
  src/app/main/bubble-chart/bubble/bubble.component.html
  src/app/main/bubble-chart/scatter/scatter.component.html
  src/app/main/home/home.component.html
  src/app/main/home/home.component.scss
  src/app/main/line-chart/line/line.component.html
  src/app/main/line-chart/line/line.component.ts
  src/app/main/line-chart/lineplusbar/lineplusbar.component.html
  src/app/main/line-chart/ohlc/ohlc.component.html
  src/app/main/line-chart/parallel-coordinates/parallel-coordinates.component.html
  src/app/main/main-theme.scss
  src/app/main/other-charts/candlestick/candlestick.component.html
  src/app/main/other-charts/directed-graph/directed-graph.component.html
  src/app/main/other-charts/donut/donut.component.html
  src/app/main/other-charts/donut/donut.component.ts
  src/app/main/other-charts/pie/pie.component.html
  src/app/main/other-charts/pie/pie.component.ts
  src/app/shared/chart/custom.chart.component.ts
  src/app/shared/example/example.component.html
  src/app/shared/example/example.component.scss
  src/app/shared/example/example.theme.scss
  src/app/shared/highlight/highlight.component.html
  src/app/shared/highlight/highlight.component.scss
  src/app/shared/highlight/highlight.component.ts
  src/app/shared/shared.module.ts
  src/assets/css/app.scss
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/styles.scss
Labels: release
