Repository OntimizeWeb/ontimize-web-ngx-charts, pull requests merged in 2024-07, with the labels that each got.

#250 [15.1.2] Fixed bug with custom chart values with static data
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
Labels: bug

#249 [15.1.2] Added new inputs showXAxisLabel and showYAxisLabel
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
Labels: enhancement

#252 [15.1.2] Modified translations in load preferences dialog
  projects/ontimize-web-ngx-charts/src/lib/components/chart-on-demand/load-preferences-dialog/load-preferences-dialog.component.html
  projects/ontimize-web-ngx-charts/src/lib/i18n/i18n.ts
Labels: bug

#253 [15.1.2] CHANGELOG
  CHANGELOG.md
Labels: enhancement

#248 Hotfix 15.1.2
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx-charts/package.json
  projects/ontimize-web-ngx-charts/src/lib/components/chart-on-demand/load-preferences-dialog/load-preferences-dialog.component.html
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
  projects/ontimize-web-ngx-charts/src/lib/i18n/i18n.ts
Labels: release
