Repository OntimizeWeb/ontimize-web-ngx-charts, pull requests merged in 2024-05, with the labels that each got.

#215 [15.0.1] Added show-grid-lines to charts
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.html
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
Labels: bug

#216 [15.0.1] Fixed bug with height and width
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
Labels: bug

#213 Hotfix 15.0.1
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx-charts/package.json
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.html
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
Labels: release

#223 [15.x.x] Created new inputs xformatting and yformatting
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
Labels: enhancement

#222 [15.x.x] Added the posibility to customize the legend
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
Labels: enhancement

#225 [15.x.x] Added outputs to charts
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.html
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
Labels: enhancement

#226 [15.1.0] Changelog
  CHANGELOG.md
Labels: enhancement

#227 Release 15.1.0
  .github/CODEOWNERS
  .github/workflows/build-ci.yml
  .github/workflows/build-manually.yml
  .github/workflows/deploy-snapshot-nexus.yml
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx-charts/README.md
  projects/ontimize-web-ngx-charts/package.json
  projects/ontimize-web-ngx-charts/src/lib/components/chart-on-demand/o-chart-on-demand.component.html
  projects/ontimize-web-ngx-charts/src/lib/components/chart-on-demand/o-chart-on-demand.component.scss
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.html
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
  projects/ontimize-web-ngx-charts/src/public-api.ts
Labels: release

#230 [Quickstart Charts] Release 15.3.0
  charts/ontimize-web-ngx-charts/values.yaml
  package-lock.json
  package.json
Labels: release

#233 [Quickstart Charts] Release 8.3.0
  charts/ontimize-web-ngx-charts/values.yaml
  package-lock.json
  package.json
Labels: release

#235 [Quickstart Charts] Hotfix 8.3.1
  charts/ontimize-web-ngx-charts/values.yaml
  package-lock.json
  package.json
Labels: release
