Repository OntimizeWeb/ontimize-web-ngx-charts, pull requests merged in 2024-10, with the labels that each got.

#265 [15.1.3] Added autoscale to line charts
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.html
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
Labels: enhancement

#263 [15.1.3] Modified pie configuration
  projects/ontimize-web-ngx-charts/src/lib/components/chart-on-demand/o-chart-on-demand-utils.ts
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
  projects/ontimize-web-ngx-charts/src/lib/models/options/PieChartConfiguration.class.ts
  projects/ontimize-web-ngx-charts/src/lib/models/options/PieChartOptions.class.ts
Labels: bug

#268 [15.1.3] CHANGELOG
  CHANGELOG.md
Labels: enhancement

#260 Hotfix 15.1.3
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx-charts/package.json
  projects/ontimize-web-ngx-charts/src/lib/components/chart-on-demand/o-chart-on-demand-utils.ts
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.html
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.scss
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
  projects/ontimize-web-ngx-charts/src/lib/models/options/PieChartConfiguration.class.ts
  projects/ontimize-web-ngx-charts/src/lib/models/options/PieChartOptions.class.ts
Labels: release

#256 [Quickstart-charts] [15.x.x] Added dynamic chart generator
  angular.json
  package-lock.json
  package.json
  src/app/main/area-chart/stacked-area/stacked-area.component.html
  src/app/main/area-chart/stacked-area/stacked-area.component.ts
  src/app/main/bar-chart/multi-bar-horizontal/multi-bar-horizontal.component.html
  src/app/main/bar-chart/multi-bar/multi-bar.component.html
  src/app/main/custom-chart/custom-chart-routing.module.ts
  src/app/main/custom-chart/custom-chart.component.html
  src/app/main/custom-chart/custom-chart.component.scss
  src/app/main/custom-chart/custom-chart.component.ts
  src/app/main/custom-chart/custom-chart.module.ts
  src/app/main/data-input-dialog/data-input-dialog.component.html
  src/app/main/data-input-dialog/data-input-dialog.component.scss
  src/app/main/data-input-dialog/data-input-dialog.component.spec.ts
  src/app/main/data-input-dialog/data-input-dialog.component.ts
  src/app/main/home/home.component.html
  src/app/main/main-routing.module.ts
  src/app/main/main.module.ts
  src/app/main/other-charts/donut/donut.component.html
  src/app/main/other-charts/donut/donut.component.ts
  src/app/main/other-charts/pie/pie.component.html
  src/app/main/other-charts/pie/pie.component.ts
  src/app/shared/app.menu.config.ts
  src/app/shared/example/example.component.html
  src/app/shared/example/example.component.ts
  src/assets/chart_animation.svg
  src/assets/i18n/en.json
  src/assets/i18n/es.json
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: enhancement

#272 [Quickstart Charts] Release 15.4.0
  angular.json
  charts/ontimize-web-ngx-charts/values.yaml
  package-lock.json
  package.json
  src/app/main/area-chart/stacked-area/stacked-area.component.html
  src/app/main/area-chart/stacked-area/stacked-area.component.ts
  src/app/main/bar-chart/multi-bar-horizontal/multi-bar-horizontal.component.html
  src/app/main/bar-chart/multi-bar/multi-bar.component.html
  src/app/main/custom-chart/custom-chart-routing.module.ts
  src/app/main/custom-chart/custom-chart.component.html
  src/app/main/custom-chart/custom-chart.component.scss
  src/app/main/custom-chart/custom-chart.component.ts
  src/app/main/custom-chart/custom-chart.module.ts
  src/app/main/data-input-dialog/data-input-dialog.component.html
  src/app/main/data-input-dialog/data-input-dialog.component.scss
  src/app/main/data-input-dialog/data-input-dialog.component.spec.ts
  src/app/main/data-input-dialog/data-input-dialog.component.ts
  src/app/main/home/home.component.html
  src/app/main/main-routing.module.ts
  src/app/main/main.module.ts
  src/app/main/other-charts/donut/donut.component.html
  src/app/main/other-charts/donut/donut.component.ts
  src/app/main/other-charts/pie/pie.component.html
  src/app/main/other-charts/pie/pie.component.ts
  src/app/shared/app.menu.config.ts
  src/app/shared/example/example.component.html
  src/app/shared/example/example.component.ts
  src/assets/chart_animation.svg
  src/assets/i18n/en.json
  src/assets/i18n/es.json
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: release

#274 [Quickstart Charts] Hotfix 15.4.1
  charts/ontimize-web-ngx-charts/values.yaml
  package-lock.json
  package.json
Labels: release
