Repository OntimizeWeb/ontimize-web-ngx-charts, pull requests merged in 2025-03, with the labels that each got.

#288 [15.1.4] Updated chart margins
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
Labels: enhancement

#277 Hotfix 15.1.4
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx-charts/package.json
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.html
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
  projects/ontimize-web-ngx-charts/src/lib/i18n/i18n.ts
  projects/ontimize-web-ngx-charts/src/lib/models/options/ChartConfiguration.class.ts
Labels: release

#292 [Jsonapi] Update version
  CHANGELOG.md
  ontimize-web-ngx-15.1.0-JSONAPI-SNAPSHOT-11.tgz
  package-lock.json
  package.json
  projects/ontimize-web-ngx-charts/package.json
  projects/ontimize-web-ngx-charts/src/lib/components/chart-on-demand/load-preferences-dialog/load-preferences-dialog.component.html
  projects/ontimize-web-ngx-charts/src/lib/components/chart-on-demand/o-chart-on-demand.component.ts
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.html
  projects/ontimize-web-ngx-charts/src/lib/components/chart/o-chart.component.ts
  projects/ontimize-web-ngx-charts/src/lib/i18n/i18n.ts
  projects/ontimize-web-ngx-charts/src/lib/models/options/ChartConfiguration.class.ts
Labels: snapshot

#295 [Quickstart Charts] Release 15.5.0
  charts/ontimize-web-ngx-charts/values.yaml
  package-lock.json
  package.json
  src/app/main/line-chart/line/line.component.html
  src/app/main/line-chart/line/line.component.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: release

#300 Hotfix 15.1.5
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx-charts/package.json
  projects/ontimize-web-ngx-charts/src/lib/components/chart-on-demand/o-chart-on-demand.component.ts
Labels: release
